import {
  Transfer,
  TransferAmount,
  TransferStatus,
  TransferType,
} from "#payments/transfer/domain";

export const TRANSACTION_FIXTURES = [
  Transfer.create({
    amount: TransferAmount.create(1500.0),
    date: new Date("2024-06-24T10:30:00"),
    description: "Transferencia a María García",
    id: "txn-001",
    recipientId: "contact-1",
    status: TransferStatus.success(),
    type: TransferType.expense(),
    userId: "user-1",
  }),
  Transfer.create({
    amount: TransferAmount.create(3200.5),
    date: new Date("2024-06-23T15:45:00"),
    description: "Pago recibido de Juan Pérez",
    id: "txn-002",
    recipientId: "contact-2",
    status: TransferStatus.success(),
    type: TransferType.income(),
    userId: "user-1",
  }),
  Transfer.create({
    amount: TransferAmount.create(850.0),
    date: new Date("2024-06-22T09:15:00"),
    description: "Compra en Amazon",
    id: "txn-003",
    recipientId: "contact-3",
    status: TransferStatus.success(),
    type: TransferType.expense(),
    userId: "user-1",
  }),
  Transfer.create({
    amount: TransferAmount.create(500.0),
    date: new Date("2024-06-21T18:20:00"),
    description: "Transferencia a Carlos López",
    id: "txn-004",
    recipientId: "contact-4",
    status: TransferStatus.pending(),
    type: TransferType.expense(),
    userId: "user-2",
  }),
  Transfer.create({
    amount: TransferAmount.create(2100.0),
    date: new Date("2024-06-20T12:00:00"),
    description: "Pago de nómina",
    id: "txn-005",
    recipientId: "contact-5",
    status: TransferStatus.success(),
    type: TransferType.income(),
    userId: "user-2",
  }),
  Transfer.create({
    amount: TransferAmount.create(450.75),
    date: new Date("2024-06-19T14:30:00"),
    description: "Pago de servicios",
    id: "txn-006",
    recipientId: "contact-6",
    status: TransferStatus.failed(),
    type: TransferType.expense(),
    userId: "user-2",
  }),
  Transfer.create({
    amount: TransferAmount.create(1200.0),
    date: new Date("2024-06-18T11:00:00"),
    description: "Transferencia recibida",
    id: "txn-007",
    recipientId: "contact-7",
    status: TransferStatus.success(),
    type: TransferType.income(),
    userId: "user-3",
  }),
  Transfer.create({
    amount: TransferAmount.create(680.0),
    date: new Date("2024-06-17T16:45:00"),
    description: "Compra en supermercado",
    id: "txn-008",
    recipientId: "contact-8",
    status: TransferStatus.success(),
    type: TransferType.expense(),
    userId: "user-3",
  }),
];
